version: '3.8'

services:
  app:
    build: .
    container_name: payroll_app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - app-net

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-net

  redis:
    image: redis:7
    container_name: redis_cache
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-net

volumes:
  postgres_data:
  redis_data:

networks:
  app-net: